### ISSUE TITLE
Add Comments to explain basics

### ISSUE THREAD

**Issue by jacueblol** [Patribots4738/Differential-Drive-Command-Based#5]

**Comment by jacueblol** [comment]
What do you think of these comments @GalexY727? I think they sound pretty good to me, however, if there is anything that you think is required, please add and link to this issue.

**Comment by GalexY727** [comment]
I think it might be important to note that mode specific periodics like teleopPeriodic runs before robotPeriodic, but command based doesn't really use the mode periodics much so it likely won't matter.

**Comment by GalexY727** [comment]
@Jacob1010-h

**Comment by jacueblol** [comment]
Sorry about missing this comment! I yes I completely agree, it might be something important to note, however, rarely is the periodic methods ever used so it shouldn't matter much.
